services:
  mongo:
    image: mongo:8
    container_name: blog_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: blog_user
      MONGO_INITDB_ROOT_PASSWORD: blog_pass
      MONGO_INITDB_DATABASE: blog_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
